apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
        env: # this image was previously configured to receive this env vars
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret # mongo-secret.metadata.name
              key: mongo-user # mongo-secret.data
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mongo-secret # mongo-secret.metadata.name
              key: mongo-password # mongo-secret.data
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config # mongo-config.metadata.name
              key: mongo-url # mongo-config.data
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service # matches mongo-config.data.mongo-url
spec:
  type: NodePort
  selector:
    app: webapp # match Deployment.spec.template.metadata.labels
  ports:
    - protocol: TCP
      port: 3000 # can by any port (best practice to be equal to targetPort)
      targetPort: 3000 # port of the pod
      nodePort: 30100 # exposes the service on each node's ip at a static port. Only defined because type: NodePort. Must be in the range of 30000-32767
