apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-10-29T21:51:06Z"
  labels:
    app: jupyter-app
  name: jupyter-svc
  namespace: jupyter
  resourceVersion: "3638"
  uid: f5ddac51-634f-41e4-af90-cd07f247a10e
spec:
  clusterIP: 10.100.65.188
  clusterIPs:
  - 10.100.65.188
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30000
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: jupyter-pods
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
