apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: my-daemonset
  labels:
    app: frontend

spec:
  # opcional
  updateStrategy:
    type: OnDelete # o pod só é atualizado quando o pod atual é deletado

    # type: RollingUpdate # pod é atualizado em qualquer modificação (estratégia default)
    # rollingUpdate:
    #   maxUnavailable: 2 # qtde max de pods que podem ficar indisponíveis durante atualizacao (default = 1)


  template:
    metadata:
      name: my-pod-webserver
      labels:
        apps: my-app
        tier: frontend
    spec:
      containers:
      - name: my-container-nginx
        image: tomcat

      # ativa o daemonset somente nos nodes com a label abaixo
      # nodeSelector: 
        # disktype: ssd
      
      # ativa o daemonset em um node com nome especifico
      # nodeName: minikube-m03

  selector:
    matchLabels:
      apps: my-app
