apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: kubernetes.io/basic-auth # nesse tipo, 'username' e 'password' são obrigatórios

# stringData:
#   username: admin
#   password: pass-123

# em data, os valores devem ser codificados em base64
data:
  username: YWRtaW4=
  password: cGFzcy0xMjMK
  extra-key: cGFzcy0xMjMK

# extra keys, caso necessário
stringData:
  extra2: value2
